import { motion } from "framer-motion";
import {
  FaGlobeAsia,
  FaCloudSun,
  FaSuitcase,
  FaShieldAlt,
  FaHandsHelping,
  FaPhoneAlt,
  FaCheckCircle,
  FaMagic,
} from "react-icons/fa";

const InfoCard = ({ icon, title, children }) => {
  return (
    <div className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-md rounded-3xl p-6 border border-slate-200/60 dark:border-slate-700/60 shadow-lg">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center">
          {icon}
        </div>

        <h3 className="font-bold text-lg text-slate-800 dark:text-white">
          {title}
        </h3>
      </div>

      {children}
    </div>
  );
};

const CompanionSection = ({ trip, companionLoading, onGenerateCompanion }) => {
  const hasCompanion = !!trip?.travelCompanion?.bestSeason;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.7 }}
      className="mt-6"
    >
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 rounded-2xl bg-slate-700 dark:bg-slate-600 flex items-center justify-center text-white shadow-lg">
            <FaMagic size={18} />
          </div>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white">
            Travel Guide & Essentials
          </h2>
        </div>

        <p className="text-slate-600 dark:text-slate-400 leading-relaxed mb-5 max-w-3xl">
          Get useful travel information generated by AI to help you prepare for
          your journey. Discover the best time to visit, weather expectations,
          packing suggestions, safety recommendations, local customs, and
          emergency contact information for your destination.
        </p>

        {!hasCompanion && (
          <motion.button
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            whileHover={{ scale: companionLoading ? 1 : 1.02 }}
            whileTap={{ scale: companionLoading ? 1 : 0.98 }}
            onClick={onGenerateCompanion}
            disabled={companionLoading}
            className="bg-slate-700 dark:bg-slate-600 hover:bg-slate-800 dark:hover:bg-slate-500 text-white px-6 py-3 rounded-2xl font-semibold shadow-lg transition-all disabled:opacity-50"
          >
            {companionLoading
              ? "Generating Travel Guide..."
              : "Generate Travel Guide"}
          </motion.button>
        )}
      </div>

      {/* Generated Content */}
      {hasCompanion && (
        <div className="grid lg:grid-cols-2 gap-5">
          <InfoCard
            icon={
              <FaGlobeAsia className="text-slate-700 dark:text-slate-300" />
            }
            title="Best Season to Visit"
          >
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              {trip.travelCompanion.bestSeason}
            </p>
          </InfoCard>

          <InfoCard
            icon={<FaCloudSun className="text-slate-700 dark:text-slate-300" />}
            title="Weather Information"
          >
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              {trip.travelCompanion.weather}
            </p>
          </InfoCard>

          <InfoCard
            icon={<FaSuitcase className="text-slate-700 dark:text-slate-300" />}
            title="Packing Checklist"
          >
            <ul className="space-y-3">
              {trip.travelCompanion.packingChecklist?.map((item, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 text-slate-600 dark:text-slate-400"
                >
                  <FaCheckCircle className="mt-1 text-slate-500 shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </InfoCard>

          <InfoCard
            icon={
              <FaShieldAlt className="text-slate-700 dark:text-slate-300" />
            }
            title="Safety Tips"
          >
            <ul className="space-y-3">
              {trip.travelCompanion.safetyTips?.map((item, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 text-slate-600 dark:text-slate-400"
                >
                  <FaCheckCircle className="mt-1 text-slate-500 shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </InfoCard>

          <InfoCard
            icon={
              <FaHandsHelping className="text-slate-700 dark:text-slate-300" />
            }
            title="Local Etiquette"
          >
            <ul className="space-y-3">
              {trip.travelCompanion.localEtiquette?.map((item, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 text-slate-600 dark:text-slate-400"
                >
                  <FaCheckCircle className="mt-1 text-slate-500 shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </InfoCard>

          <InfoCard
            icon={<FaPhoneAlt className="text-slate-700 dark:text-slate-300" />}
            title="Emergency Contacts"
          >
            <ul className="space-y-3">
              {trip.travelCompanion.emergencyNumbers?.map((item, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 text-slate-600 dark:text-slate-400"
                >
                  <FaCheckCircle className="mt-1 text-slate-500 shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </InfoCard>
        </div>
      )}
    </motion.div>
  );
};

export default CompanionSection;
